from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically calculate and draw total page count and footer."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        # Do not render header/footer on cover page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#4A5568"))

        # Footer divider line
        self.setStrokeColor(colors.HexColor("#CBD5E0"))
        self.setLineWidth(0.5)
        self.line(54, 40, 558, 40)

        # Footer text
        self.drawString(54, 25, "Generated by APIRecon")
        self.drawRightString(558, 25, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()


def add_section_title(title_text, styles):
    """Helper function to create styled section titles."""
    return Paragraph(f"<b>{title_text}</b>", styles["SectionHeader"])


def create_table(data, col_widths, is_header=True):
    """Helper function to create formatted tables with wrapped paragraphs and alternating colors."""
    if not data:
        return None

    table_style = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#008080")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
    ]

    # Add alternating row background colors
    for i in range(1, len(data)):
        if i % 2 == 0:
            table_style.append(
                ("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F7FAFC"))
            )

    t = Table(data, colWidths=col_widths, repeatRows=1 if is_header else 0)
    t.setStyle(TableStyle(table_style))
    return t


def generate_report(analysis):
    pdf_filename = "APIRecon_Report.pdf"

    # Setup document geometry (Letter, 0.75 in / 54 pt margins)
    doc = SimpleDocTemplate(
        pdf_filename,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    # Styles Setup
    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="CoverTitle",
            fontName="Helvetica-Bold",
            fontSize=32,
            leading=38,
            textColor=colors.HexColor("#008080"),
            alignment=0,
            spaceAfter=10,
        )
    )

    styles.add(
        ParagraphStyle(
            name="CoverSubtitle",
            fontName="Helvetica",
            fontSize=16,
            leading=22,
            textColor=colors.HexColor("#2D3748"),
            alignment=0,
            spaceAfter=30,
        )
    )

    styles.add(
        ParagraphStyle(
            name="CoverMetaLabel",
            fontName="Helvetica-Bold",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#008080"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="CoverMetaValue",
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#2D3748"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="SectionHeader",
            fontName="Helvetica-Bold",
            fontSize=14,
            leading=18,
            textColor=colors.HexColor("#008080"),
            spaceBefore=12,
            spaceAfter=8,
            keepWithNext=True,
        )
    )

    styles.add(
        ParagraphStyle(
            name="TableHeader",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=11,
            textColor=colors.white,
        )
    )

    styles.add(
        ParagraphStyle(
            name="TableCell",
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1A202C"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="TableCellBold",
            fontName="Helvetica-Bold",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1A202C"),
        )
    )

    styles.add(
        ParagraphStyle(
            name="NoDataCell",
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#718096"),
            alignment=1,
        )
    )

    elements = []

    # =========================================================================
    # COVER PAGE
    # =========================================================================
    elements.append(Spacer(1, 100))
    elements.append(Paragraph("APIRecon", styles["CoverTitle"]))
    elements.append(
        Paragraph(
            "Postman Collection Security Analysis Report",
            styles["CoverSubtitle"],
        )
    )

    # Decorative accent line
    dec_table = Table([[""]], colWidths=[504], rowHeights=[4])
    dec_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#008080")),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    elements.append(dec_table)
    elements.append(Spacer(1, 200))

    # Collection Metadata Block
    col_info = analysis.get("collection", {})

    meta_data = [
        [
            Paragraph("Target Collection:", styles["CoverMetaLabel"]),
            Paragraph(
                str(col_info.get("name", "N/A")), styles["CoverMetaValue"]
            ),
        ],
        [
            Paragraph("Postman ID:", styles["CoverMetaLabel"]),
            Paragraph(
                str(col_info.get("postman_id", "N/A")), styles["CoverMetaValue"]
            ),
        ],
        [
            Paragraph("Schema:", styles["CoverMetaLabel"]),
            Paragraph(
                str(col_info.get("schema", "N/A")), styles["CoverMetaValue"]
            ),
        ],
    ]

    meta_table = Table(meta_data, colWidths=[120, 384])
    meta_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )
    elements.append(meta_table)
    elements.append(PageBreak())

    # =========================================================================
    # EXECUTIVE SUMMARY
    # =========================================================================
    elements.append(add_section_title("Executive Summary", styles))

    summary = analysis.get("summary", {})
    vars_info = analysis.get("variables", {})

    tot_requests = summary.get("total_requests", 0)
    tot_folders = summary.get("total_folders", 0)
    tot_vars = (
        vars_info.get("count", len(vars_info.get("items", [])))
        if isinstance(vars_info, dict)
        else 0
    )
    tot_sensitive = len(analysis.get("sensitive_data", []))
    tot_endpoints = len(analysis.get("endpoints", []))

    exec_data = [
        [
            Paragraph("Metric", styles["TableHeader"]),
            Paragraph("Count", styles["TableHeader"]),
        ],
        [
            Paragraph("Total Endpoints", styles["TableCellBold"]),
            Paragraph(str(tot_endpoints), styles["TableCell"]),
        ],
        [
            Paragraph("Total Requests", styles["TableCellBold"]),
            Paragraph(str(tot_requests), styles["TableCell"]),
        ],
        [
            Paragraph("Total Folders", styles["TableCellBold"]),
            Paragraph(str(tot_folders), styles["TableCell"]),
        ],
        [
            Paragraph("Total Variables", styles["TableCellBold"]),
            Paragraph(str(tot_vars), styles["TableCell"]),
        ],
        [
            Paragraph("Total Sensitive Findings", styles["TableCellBold"]),
            Paragraph(str(tot_sensitive), styles["TableCell"]),
        ],
    ]

    elements.append(create_table(exec_data, [354, 150]))
    elements.append(Spacer(1, 15))

    # =========================================================================
    # SENSITIVE DATA FINDINGS
    # =========================================================================
    elements.append(add_section_title("Sensitive Data Findings", styles))

    sens_list = analysis.get("sensitive_data", [])
    if sens_list:
        sens_data = [
            [
                Paragraph("Key / Finding", styles["TableHeader"]),
                Paragraph("Severity", styles["TableHeader"]),
                Paragraph("Location", styles["TableHeader"]),
                Paragraph("Method", styles["TableHeader"]),
                Paragraph("Endpoint", styles["TableHeader"]),
            ]
        ]

        styles.add(
            ParagraphStyle(
                name="SevHigh",
                fontName="Helvetica-Bold",
                fontSize=9,
                textColor=colors.HexColor("#DC2626"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="SevMedium",
                fontName="Helvetica-Bold",
                fontSize=9,
                textColor=colors.HexColor("#D97706"),
            )
        )
        styles.add(
            ParagraphStyle(
                name="SevLow",
                fontName="Helvetica-Bold",
                fontSize=9,
                textColor=colors.HexColor("#16A34A"),
            )
        )

        for item in sens_list:
            sev = str(item.get("severity", "Low")).strip().capitalize()
            if sev == "High":
                sev_p = Paragraph("High", styles["SevHigh"])
            elif sev == "Medium":
                sev_p = Paragraph("Medium", styles["SevMedium"])
            else:
                sev_p = Paragraph("Low", styles["SevLow"])

            sens_data.append(
                [
                    Paragraph(
                        str(item.get("key", "N/A")), styles["TableCellBold"]
                    ),
                    sev_p,
                    Paragraph(
                        str(item.get("location", "N/A")), styles["TableCell"]
                    ),
                    Paragraph(
                        str(item.get("method", "N/A")), styles["TableCell"]
                    ),
                    Paragraph(
                        str(item.get("endpoint", "N/A")), styles["TableCell"]
                    ),
                ]
            )
        elements.append(
            create_table(sens_data, [110, 60, 84, 50, 200])
        )
    else:
        no_sens = [
            [
                Paragraph(
                    "No Sensitive Data Found", styles["NoDataCell"]
                )
            ]
        ]
        elements.append(create_table(no_sens, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # ENDPOINTS
    # =========================================================================
    elements.append(add_section_title("Endpoints", styles))

    endpoints_list = analysis.get("endpoints", [])
    if endpoints_list:
        ep_data = [
            [
                Paragraph("Method", styles["TableHeader"]),
                Paragraph("URL", styles["TableHeader"]),
                Paragraph("Auth", styles["TableHeader"]),
            ]
        ]
        for ep in endpoints_list:
            ep_data.append(
                [
                    Paragraph(
                        str(ep.get("method", "N/A")), styles["TableCellBold"]
                    ),
                    Paragraph(str(ep.get("url", "N/A")), styles["TableCell"]),
                    Paragraph(
                        str(ep.get("auth", "N/A")), styles["TableCell"]
                    ),
                ]
            )
        elements.append(create_table(ep_data, [70, 314, 120]))
    else:
        no_ep = [[Paragraph("No Endpoints Found", styles["NoDataCell"])]]
        elements.append(create_table(no_ep, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # HTTP METHODS SUMMARY
    # =========================================================================
    elements.append(add_section_title("HTTP Methods Summary", styles))

    methods_dict = analysis.get("methods", {})
    if methods_dict:
        m_data = [
            [
                Paragraph("Method", styles["TableHeader"]),
                Paragraph("Count", styles["TableHeader"]),
            ]
        ]
        for m_name, count in methods_dict.items():
            m_data.append(
                [
                    Paragraph(str(m_name), styles["TableCellBold"]),
                    Paragraph(str(count), styles["TableCell"]),
                ]
            )
        elements.append(create_table(m_data, [252, 252]))
    else:
        no_m = [[Paragraph("No Methods Found", styles["NoDataCell"])]]
        elements.append(create_table(no_m, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # AUTHENTICATION METHODS
    # =========================================================================
    elements.append(add_section_title("Authentication Methods", styles))

    auth_dict = analysis.get("authentication", {})
    if auth_dict:
        auth_data = [
            [
                Paragraph("Auth Type", styles["TableHeader"]),
                Paragraph("Count", styles["TableHeader"]),
            ]
        ]
        for a_type, count in auth_dict.items():
            auth_data.append(
                [
                    Paragraph(str(a_type), styles["TableCellBold"]),
                    Paragraph(str(count), styles["TableCell"]),
                ]
            )
        elements.append(create_table(auth_data, [252, 252]))
    else:
        no_auth = [[Paragraph("No Authentication Found", styles["NoDataCell"])]]
        elements.append(create_table(no_auth, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # VARIABLES
    # =========================================================================
    elements.append(add_section_title("Variables", styles))

    vars_items = []
    if isinstance(vars_info, dict):
        vars_items = vars_info.get("items", [])

    if vars_items:
        v_data = [
            [
                Paragraph("Key", styles["TableHeader"]),
                Paragraph("Value", styles["TableHeader"]),
            ]
        ]
        for v in vars_items:
            v_data.append(
                [
                    Paragraph(
                        str(v.get("key", "N/A")), styles["TableCellBold"]
                    ),
                    Paragraph(str(v.get("value", "N/A")), styles["TableCell"]),
                ]
            )
        elements.append(create_table(v_data, [200, 304]))
    else:
        no_vars = [[Paragraph("No Variables Found", styles["NoDataCell"])]]
        elements.append(create_table(no_vars, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # HEADERS
    # =========================================================================
    elements.append(add_section_title("Headers", styles))

    headers_dict = analysis.get("headers", {})
    if headers_dict:
        h_data = [
            [
                Paragraph("Header Key", styles["TableHeader"]),
                Paragraph("Occurrences / Value", styles["TableHeader"]),
            ]
        ]
        for h_key, h_val in headers_dict.items():
            h_data.append(
                [
                    Paragraph(str(h_key), styles["TableCellBold"]),
                    Paragraph(str(h_val), styles["TableCell"]),
                ]
            )
        elements.append(create_table(h_data, [250, 254]))
    else:
        no_h = [[Paragraph("No Headers Found", styles["NoDataCell"])]]
        elements.append(create_table(no_h, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # QUERY PARAMETERS
    # =========================================================================
    elements.append(add_section_title("Query Parameters", styles))

    qp_dict = analysis.get("query_parameters", {})
    if qp_dict:
        qp_data = [
            [
                Paragraph("Parameter Key", styles["TableHeader"]),
                Paragraph("Occurrences / Value", styles["TableHeader"]),
            ]
        ]
        for q_key, q_val in qp_dict.items():
            qp_data.append(
                [
                    Paragraph(str(q_key), styles["TableCellBold"]),
                    Paragraph(str(q_val), styles["TableCell"]),
                ]
            )
        elements.append(create_table(qp_data, [250, 254]))
    else:
        no_qp = [
            [Paragraph("No Query Parameters Found", styles["NoDataCell"])]
        ]
        elements.append(create_table(no_qp, [504], is_header=False))

    elements.append(Spacer(1, 15))

    # =========================================================================
    # RESPONSES
    # =========================================================================
    elements.append(add_section_title("Responses", styles))

    resp_list = analysis.get("response", [])
    if resp_list:
        r_data = [
            [
                Paragraph("Status", styles["TableHeader"]),
                Paragraph("Code", styles["TableHeader"]),
            ]
        ]
        for r in resp_list:
            r_data.append(
                [
                    Paragraph(
                        str(r.get("status", "N/A")), styles["TableCell"]
                    ),
                    Paragraph(
                        str(r.get("code", "N/A")), styles["TableCellBold"]
                    ),
                ]
            )
        elements.append(create_table(r_data, [354, 150]))
    else:
        no_resp = [[Paragraph("No Responses Found", styles["NoDataCell"])]]
        elements.append(create_table(no_resp, [504], is_header=False))

    # Build the document with dynamic header/footer canvas
    doc.build(elements, canvasmaker=NumberedCanvas)